### ISSUE TITLE
Align on cdVersionNumber field for Model-Version and Certify-Model record

### ISSUE THREAD

**Issue by jcps07** [Comcast/dcl-ui#14]
By Spec, the cdVersionNumber must match  in 3 places: Certification Declaration, Device Model Version and Compliance Record... and it should be defined by the CSA, but it was first input by the Model-Version and the parameter is missing when submitting a Compliance Record. So we agreed that it will be hardcoded to "1".

We have 2 options:
1. Add cdVersionNumber field in the "Certify Model" form and make sure they are the same "1"
2. Remove cdVersionNumber field from "Add New Model Version" and make sure it is "1" when submitted at "Model Version" and "Certify Model"

Recommended approach No. 2

**Comment by jcps07** [comment]
Option 3: Pre-populate "cdVersionNumber" field with a "1" (instead of blank or 0), when adding a new model-version.

**Comment by ankur325** [comment]
CDVersionNumber is now defaulted to 1, when adding a new model version.

**Comment by jcps07** [comment]
Could you please make the field as disabled to avoid members overwriting the default value?
