### ISSUE TITLE
NFR: Add a link next to the Model-Version to Certify Model-Version

### ISSUE THREAD

**Issue by jcps07** [Comcast/dcl-ui#15]
When a Model-Version is to be certified, it requires the Model-Version to be in the DCL and then input some data from that Model-Version to the "Certify Model-Version" form. It'd make it easier if there is a link next to each record to allow Certification Center to click on it and easily certify it, with the required fields already populated (VID, PID, SWVersion, SWVersionString), other fields will be entered by CertificationCenter account.

**Comment by ankur325** [comment]
This was implemented, hence closing it
