### ISSUE TITLE
Display some information in Hex format

### ISSUE THREAD

**Issue by jcps07** [Comcast/dcl-ui#18]
Enhancement:
Currently, the DCL uses decimal values for all numeric fields but it'd be good to visualize in Hex format, at least: VID, PID & Device_Type .
In order to avoid misinterpretation from actual value from DCL, it could be shown in parenthesis on the right, ie:
     VID                          PID
12288 (0x3000)     4096 (0x1000)

**Comment by ankur325** [comment]
This was implemented in 1.0.6
