### ISSUE TITLE
VendorInfo schema: Typo and Value on "Company Preferred Name"

### ISSUE THREAD

**Issue by jcps07** [Comcast/dcl-ui#19]
Bug report (webUI) for VendorInfo:   

1. Typo "Preffered" should be "Preferred"
2. Value of "Preferred Vendor Name" is not passed to the DCL

![image](https://user-images.githubusercontent.com/14283437/209208574-bad022e0-9156-467d-a19f-077eb5ae58dc.png)

dcld CLI client works as expected.

Slack conv: https://csamembers.slack.com/archives/C025PQ6RMRA/p1671735915670699

**Comment by ankur325** [comment]
This was fixed in 1.0.6
