### ISSUE TITLE
Add Model-Version: WebUI asks for "Firmware Digests" instead of "FirmwareInformation" (firmwareInformation in DCL)

### ISSUE THREAD

**Issue by jcps07** [Comcast/dcl-ui#23]
When adding a Model-Version, the WebUI asks for "Firmware Digests" instead of "Firmware Information" (firmwareInformation in DCL).
Meaning that it doesn't populate in the DCL and that field is not Mutable, so no way to fix it.

![image](https://user-images.githubusercontent.com/14283437/214891254-b2fb9557-6a49-4f0b-9b2c-dc1d30bedaa1.png)

![image](https://user-images.githubusercontent.com/14283437/214891642-892d2196-590c-463f-8f37-23f87e334efd.png)

**Comment by ankur325** [comment]
This issue was fixed in release v1.0.8
