### ISSUE TITLE
Vendor ID not listed on proposed accounts

### ISSUE THREAD

**Issue by jcps07** [Comcast/dcl-ui#32]
The Vendor ID is not populated in the "All proposed accounts" view.
![no VID](https://github.com/Comcast/dcl-ui/assets/14283437/63479a24-22b8-4fa0-8ed3-2f8633f47293)

**Comment by ankur325** [comment]
This was fixed in 1.0.12 version

![image](https://github.com/Comcast/dcl-ui/assets/6667559/59c2ed49-5dfc-4709-9c8a-1391c4a608f5)
