### ISSUE TITLE
Removing a wallet from "Legacy Wallet" section results in no Legacy-Wallet mode

### ISSUE THREAD

**Issue by jcps07** [Comcast/dcl-ui#51]
![image](https://github.com/user-attachments/assets/a84a59b8-3be2-4e42-a09f-0079485135d6)
If a wallet gets removed using the "Tools and documentation" -> "Legacy Wallet" -> "Delete", then when toggling the "Keplr" button will result in a blank, instead of the Legacy wallet mode

**Comment by ankur325** [comment]
This is fixed in #52
